name: CI

on:
  push:
    branches:
      - main
      - master
      - dev
  pull_request:
    branches:
      - main
      - master
      - dev

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x] # Utilise la dernière version 20.x automatiquement

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # Version plus récente

      - name: Setup Node.js
        uses: actions/setup-node@v4 # Version plus récente
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Cache npm pour accélérer les builds

      - name: Install dependencies
        run: npm ci

      - name: Lint (optionnel)
        run: npm run lint
        continue-on-error: true # Continue même si le lint échoue

      - name: Build TypeScript
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test
        env:
          NODE_ENV: test

      - name: Upload coverage (optionnel)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 30